source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'activerecord-jdbcmysql-adapter'

gem 'jruby-openssl'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyrhino'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '2.2.1'
gem 'kaminari'
gem "font-awesome-rails"
gem 'bootbox-rails'

gem 'puma', platforms: :jruby

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
end

group :development do
  gem 'i18n_generators'
  gem 'warbler'
  gem 'meta_request'
  gem 'better_errors'
  gem 'sextant'
end

group :test do
  gem 'capybara', '~> 2.1.0'
  gem 'factory_girl_rails', '~> 4.2.0'
  gem 'database_cleaner', '~> 1.0.1'
  gem 'timecop'
  gem 'selenium-webdriver', '~> 2.34.0'
  gem 'poltergeist'
end
